import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/url_strategy.dart';
import 'package:dartvel_example/dartvel_client/router.g.dart'; // GENERATED by dartvel_cli
import 'package:go_router/go_router.dart';

void main() {
  GoRouter.optionURLReflectsImperativeAPIs = true;
  // Use path-based URLs on web (no hash)
  usePathUrlStrategy();
  runApp(const DartvelExampleApp());
}

class DartvelExampleApp extends StatelessWidget {
  const DartvelExampleApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Dartvel Example',
      routerConfig: createDartvelRouter(),
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: const Color(0xFF6750A4),
      ),
    );
  }
}
