
import 'package:flutter/material.dart';
import '.dart_tool/dartvel_client/router.g.dart'; // GENERATED by dartvel_cli
void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Dartvel Example',
      routerConfig: createDartvelRouter(),
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: const Color(0xFF6750A4)),
    );
  }
}
