import 'dart:io';

import 'package:path/path.dart' as p;

/// A discovered `@DVStaticPaths()` provider.
class StaticPathsProvider {
  const StaticPathsProvider({
    required this.functionName,
    required this.importPath,
    this.route,
  });

  /// The annotated function's name.
  final String functionName;

  /// A `package:`-qualified import for the file declaring it.
  final String importPath;

  /// The route these paths belong to, when declared explicitly.
  final String? route;
}

/// Discovers `@DVStaticPaths()` providers and emits a manifest the static
/// generator can enumerate.
///
/// Static routes are always generated; a parameterized route cannot be unless
/// something enumerates the values to generate for it. This turns those
/// annotated functions into a typed list rather than leaving static generation
/// to guess.
class StaticPathsGenerator {
  /// Matches `@DVStaticPaths(...)` on a top-level function, capturing an
  /// explicit `route:` argument when present.
  ///
  /// The return type is deliberately loose (`Future<List<String>>`,
  /// `List<String>`, or a typedef) because the annotation, not the signature,
  /// is what marks the provider.
  static final _providerRegex = RegExp(
    r'@DVStaticPaths\s*\(([^)]*)\)\s*'
    r'(?:Future\s*<[^>]*>|[A-Za-z0-9_<>, ]+?)\s+'
    r'([A-Za-z0-9_]+)\s*\(',
    dotAll: true,
  );

  static final _routeArgRegex = RegExp(
    '''route\\s*:\\s*['"]([^'"]*)['"]''',
  );

  /// Scans [root]'s `lib/` for providers.
  static List<StaticPathsProvider> discover({
    required String root,
    required String pkgName,
  }) {
    final libDir = Directory(p.join(root, 'lib'));
    if (!libDir.existsSync()) return const <StaticPathsProvider>[];

    final providers = <StaticPathsProvider>[];

    final files = libDir
        .listSync(recursive: true)
        .whereType<File>()
        .where((file) => file.path.endsWith('.dart'))
        // Generated output must never be scanned back in, or a regenerate
        // would rediscover its own emitted references.
        .where((file) => !file.path.contains('dartvel_client'))
        .where((file) => !file.path.endsWith('.g.dart'))
        .toList()
      ..sort((a, b) => a.path.compareTo(b.path));

    for (final file in files) {
      final content = file.readAsStringSync();
      if (!content.contains('@DVStaticPaths')) continue;

      final relative =
          p.relative(file.path, from: root).replaceAll(r'\', '/');
      final importPath =
          relative.replaceFirst(RegExp(r'^lib/'), 'package:$pkgName/');

      for (final match in _providerRegex.allMatches(content)) {
        final args = match.group(1) ?? '';
        final routeMatch = _routeArgRegex.firstMatch(args);
        providers.add(
          StaticPathsProvider(
            functionName: match.group(2)!,
            importPath: importPath,
            route: routeMatch?.group(1),
          ),
        );
      }
    }

    return providers;
  }

  /// Renders the manifest source for [providers].
  static String render({
    required List<StaticPathsProvider> providers,
    required String buildId,
  }) {
    final buffer = StringBuffer()
      ..writeln('// GENERATED BY DARTVEL - DO NOT EDIT')
      ..writeln('// build: $buildId')
      ..writeln('//')
      ..writeln('// Static paths for parameterized routes, discovered from')
      ..writeln('// @DVStaticPaths() providers.')
      ..writeln();

    final imports = providers.map((p) => p.importPath).toSet().toList()..sort();
    for (final import in imports) {
      buffer.writeln("import '$import';");
    }
    if (imports.isNotEmpty) buffer.writeln();

    buffer
      ..writeln('/// A route whose parameter values are enumerated at build')
      ..writeln('/// time.')
      ..writeln('class DVStaticPathsEntry {')
      ..writeln('  const DVStaticPathsEntry({')
      ..writeln('    required this.name,')
      ..writeln('    required this.route,')
      ..writeln('    required this.resolve,')
      ..writeln('  });')
      ..writeln()
      ..writeln('  /// The provider function name.')
      ..writeln('  final String name;')
      ..writeln()
      ..writeln('  /// The route these paths belong to, if declared.')
      ..writeln('  final String? route;')
      ..writeln()
      ..writeln('  /// Produces the parameter values to generate.')
      ..writeln('  final Future<List<String>> Function() resolve;')
      ..writeln('}')
      ..writeln()
      ..writeln('/// Every discovered static-path provider.')
      ..writeln('const List<DVStaticPathsEntry> dartvelStaticPaths ='
          ' <DVStaticPathsEntry>[');

    for (final provider in providers) {
      final route = provider.route == null ? 'null' : "'${provider.route}'";
      buffer
        ..writeln('  DVStaticPathsEntry(')
        ..writeln("    name: '${provider.functionName}',")
        ..writeln('    route: $route,')
        ..writeln('    resolve: ${provider.functionName},')
        ..writeln('  ),');
    }

    buffer
      ..writeln('];')
      ..writeln()
      ..writeln('/// Resolves every provider into the concrete paths to')
      ..writeln('/// generate, keyed by provider name.')
      ..writeln('Future<Map<String, List<String>>> resolveDartvelStaticPaths()'
          ' async {')
      ..writeln('  final resolved = <String, List<String>>{};')
      ..writeln('  for (final entry in dartvelStaticPaths) {')
      ..writeln('    resolved[entry.name] = await entry.resolve();')
      ..writeln('  }')
      ..writeln('  return resolved;')
      ..writeln('}');

    return buffer.toString();
  }

  /// Discovers providers and writes the manifest.
  static Future<List<StaticPathsProvider>> generate({
    required String root,
    required String pkgName,
    required String buildId,
  }) async {
    final providers = discover(root: root, pkgName: pkgName);

    final outputDir = Directory(p.join(root, 'lib', 'dartvel_client'));
    if (!outputDir.existsSync()) outputDir.createSync(recursive: true);

    final output = File(p.join(outputDir.path, 'static_paths.g.dart'));
    output.writeAsStringSync(
      render(providers: providers, buildId: buildId),
    );

    return providers;
  }
}
