
name: dartvel_cli
description: CLI for dartvel v0.1 (routes + web client + backend configs)
version: 0.1.0
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  yaml: ^3.1.2
  path: ^1.9.0
  glob: ^2.1.2
  io: ^1.0.4
  args: ^2.5.0
  file: ^7.0.0
  watcher: ^1.1.0
  build: ^3.0.2
  dartvel_shelf:
    path: ../dartvel_shelf
dev_dependencies:
  lints: ^4.0.0
executables:
  dartvel: dartvel
