
name: dartvel_core
publish_to: 'none'
description: Core helpers (Res), types, simple CORS hint for dartvel backend
version: 0.2.1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  dartvel_shelf:
    path: ../dartvel_shelf
  async: ^2.13.1
  crypto: ^3.0.7
  http: ^1.6.0
  mime: ^1.0.4
  http_parser: ^4.0.2
  shelf_multipart: ^1.0.0
  sqlite3: ^2.9.4
  drift: ^2.14.0
  pointycastle: ^4.0.0
  dio: ^5.11.0
dev_dependencies:
  test: ^1.28.0
  build_runner: ^2.4.0
  drift_dev: ^2.14.0
