name: dartvel
publish_to: 'none'
description: Umbrella package for the Dartvel full-stack Flutter platform.
version: 0.2.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartvel_core:
    path: ../dartvel_core
  dartvel_flutter:
    path: ../dartvel_flutter
  dartvel_shelf:
    path: ../dartvel_shelf
  dartvel_cli:
    path: ../dartvel_cli

dev_dependencies:
  flutter_test:
    sdk: flutter
