name: dartvel_generator
description: Compile-time generators for readable Dartvel routing and model glue.
version: 1.0.0
publish_to: none


environment:
  sdk: ">=3.4.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.4.1
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  glob: ^2.1.2
  yaml: ^3.1.2
  path: ^1.9.0
  dartvel_core:
    path: ../dartvel_core

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  build_runner: ^2.4.8
  source_gen_test: ^1.1.0
